# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['load_data', 'shopping']

# %% ../nbs/00_core.ipynb 3
def load_data(*, data):
    """
    Load the data in .csv format
    """
    try:
        if os.path.isfile(data):
            df = pd.read_csv(data, engine='python')
            return df
    except Exception as e:
        logger.info(f'check that {data} exist in environment.yaml file {e}')     

# %% ../nbs/00_core.ipynb 5
class shopping:
    """
    Prints what you have in the shipping basket
    """
    def __init__(self, cart: List):
        self.cart = cart
        print(_)
